spring.application.name=the-gamers-place

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/the-gamers-place}
spring.data.mongodb.database=${MONGODB_DATABASE:the-gamers-place}
spring.data.mongodb.auto-index-creation=true

# Server Configuration
server.port=${PORT:8080}
server.compression.enabled=true

# GraphQL Configuration
spring.graphql.graphiql.enabled=${GRAPHIQL_ENABLED:true}

# Application Custom Properties
properties.clientHost=${CLIENT_HOST:http://localhost:1234}
properties.jwtSecretKey=${JWT_SECRET_KEY:hjnasedofhoiautf3qwe7r89q234ro23ubq2o9q24rqg23ba0}
properties.jwtValidity=${JWT_VALIDITY:7200}
properties.rutaImagenes=${IMAGES_PATH:}
